### ISSUE TITLE
Activation

### ISSUE THREAD

**Issue by izahn** [vspinu/company-math#1]
does 

``` lisp
;; global activation of the unicode symbol completion 
(add-to-list 'company-backend 'company-math-symbols-unicode)
```

as suggested in the Readme actually work? `M-x describe-variable RET company-backends` says this is variable becomes buffer local when set. Perhaps this should be 

``` lisp
;; global activation of the unicode symbol completion 
(add-to-list 'company-backends 'company-math-symbols-unicode)
```

(note "backends" vs "backend").

**Comment by vspinu** [comment]
Thanks for the typo. 

`company-backends` is not buffer local by default.  Perhaps some `company` addon makes it buffer local.

 @dgutov, what is the recommended way to customize local and global `company-backends` list? Seems pretty akward [right now](https://github.com/vspinu/company-math/). Thanks.

**Comment by izahn** [comment]
Sorry, there was a typo in my report of the typo :-(. I meant to say only that `company-backend` (singular) is buffer local and so we should add the backends provided by company-math to `company-backends` (plural). Setting `(add-to-list 'company-backends 'company-math-symbols-unicode)` does work for me so I consider this problem solved. I'm leaving the ticket open in case we want to continue the discussion of the right way to add backends to `company-backends`.

**Comment by dgutov** [comment]
@vspinu

> the recommended way to customize local and global company-backends list? Seems pretty akward

The auto-complete-mode way, which is the obvious alternative, isn't much better (and worse in some respects).

But you could use `completion-at-point-functions` API instead of `company-backends`. Aside from asynchronous invocation, it's pretty much at feature parity now. Then `add-to-list` will be replaced by `add-hook`.

**Comment by vspinu** [comment]
@dgutov, How about providing 

```
(company-register-backend 'my-backend 'foo-mode)
(company-register-backend 'my-backend '(foo-mode, bar-mode, zoo-mode ...))
(company-register-backend '(backend-1 backend-2)  '(foo-mode, bar-mode, zoo-mode ...))
```

 for local and 

```
(company-register-backend 'my-backend)
```

for global initialization? This way you can change the internals without affecting the users.

The main purpose of `company-math` is to display unicode symbols, so there is no much point in having them in `acf`. Also backends are more flexible as they allow grouping and and full control over the backend order. This is why I decided for backend implementation.

**Comment by dgutov** [comment]
> How about providing ... for local and ... for global initialization?

Probably not. We've been talking with Stefan Monnier recently, and if some things go right, `company-backends` will be scheduled for deprecation, in favor of `completion-at-point-functions`.

You're listing "full control over the backend order" as an advantage of the former. Wouldn't `company-register-backend` interfere with that?

> The main purpose of company-math is to display unicode symbols, so there is no much point in having them in acf.

Why not? Or do you mean that this package isn't used for actual completion? If you think `completion-at-point-functions` is a bad interface for your purposes for other reasons, submitting an Emacs bug report wouldn't hurt. Or maybe starting discussion on emacs-devel.

**Comment by vspinu** [comment]
> We've been talking with Stefan Monnier recently, and if some things go right, company-backends will be scheduled for deprecation, in favor of completion-at-point-functions.

Is it about inserting `company` backends directly into `completion-at-point-functions`? That would be great. 

> You're listing "full control over the backend order" as an advantage of the former. Wouldn't company-register-backend interfere with that?

You can have `:before`, `:after`, `:append`  keywords to control for the order. Be it `company-backends` or `acf`, a simple user level api for registering completion function is badly missing IMO.

> If you think completion-at-point-functions is a bad interface for your purposes for other reasons, submitting an Emacs bug report wouldn't hurt. Or maybe starting discussion on emacs-devel.

I haven't given it a careful thought as yet as I didn't get deeper into how `acf` works. In principle there should be no difference between acf list and `company-backends` list as long as the same functionality is provided. Most importantly, "grouped" backends and the ability to modify the inserted candidate after the completion. The `company-math-unicode` backend doesn't complete at point but inserts the actual unicode symbol instead of the prefix text.

**Comment by dgutov** [comment]
> Is it about inserting company backends directly into completion-at-point-functions?

More likely about converting existing backends to the completion-at-point-functions API. But the above also might happen.

> You can have :before, :after, :append keywords to control for the order.

It looks reasonable, but it's an a slippery slope: if such functions are provided, the package authors might start using them in their code, and that can mess with user customizations.

Furthermore, it's not immediately obvious to me how this approach would mesh with mode hooks and buffer-local values of company-backends. Maybe we'll have these kinds of keyword arguments in `add-hook` instead, sometime.

> Most importantly, "grouped" backends and the ability to modify the inserted candidate after the completion.

Yep, that's one obvious missing feature. You don't seem to be using it with this package, though.

> The company-math-unicode backend doesn't complete at point but inserts the actual unicode symbol instead of the prefix text.

Would that be a problem for `completion-at-point`?

BTW, why `acf`? It's `capf` or `cap`, I'd say.

**Comment by vspinu** [comment]
>  Maybe we'll have these kinds of keyword arguments in add-hook instead, sometime.

That's indeed the way to go. Would be awesome!

> >    Most importantly, "grouped" backends and the ability to modify the inserted candidate after the completion.
> 
> Yep, that's one obvious missing feature. You don't seem to be using it with this package, though.

Not directly but as user [customization](https://github.com/vspinu/company-math#activation):

```

(defun my-latex-mode-setup ()
  (setq-local company-backends
              (append '(company-math-symbols-latex
                        company-latex-commands)
                      company-backends)))
```

`math-symbols-latex` and `latex-commands` must be triggered at the same time. 

The `company-math-symbols-unicode` uses `company`'s  `post-completion` hook to insert actual unicode symbol instead of the prefix. I see that `cap` framework now understands `:exit-function` but it looks like it's not intended for the modification of the inserted text. 

Is it an ongoing discussion with Stephan on `emacs-devel`? I would like to join.

> BTW, why acf? It's capf or cap, I'd say.

Yeh ... brain glitch.

**Comment by vspinu** [comment]
> math-symbols-latex and latex-commands must be triggered at the same time

 I got confused; this is not true. It's that `company-math-symbols-unicode` and `company-latex-commands` should be better within a group, and it's indeed not described in the readme. Have to add that.

**Comment by DSamuylov** [comment]
Hi,

I also have a problem with the activation... I quite new to emacs, and I am configuring my init file now. As it is written in the readme, I put into my `init.el` file:

``` emacs-lisp
        (require 'company-math)
        ;; global activation of the unicode symbol completionp¶                         
        (add-to-list 'company-backends 'company-math-symbols-unicode)¶|                 
      ¶                                                               |                 
        ;; local configuration for TeX modes¶                         |                 
      ¶                                                               |                 
        (defun my-latex-mode-setup ()¶                                |                 
          (setq-local 'company-backends¶                              |                 
                      (append '(company-math-symbols-latex company-latex-commands)¶     
                              company-backends)))¶                    |                 
      ¶                                                               |                 
        (add-hook 'LaTeX-mode-hook 'my-latex-mode-setup)¶
```

After that it seems that `company-math-symbols-unicode` is active in any mode (I checked in scratch):

<img width="240" alt="screen shot 2015-11-06 at 00 50 59" src="https://cloud.githubusercontent.com/assets/4727216/10985331/a59ec47a-8420-11e5-9a21-de4b60c8ac0d.png">

If I start typing in LateX mode, I still have `company-math-symbols-unicode` working. However it seems that I don't have other 3 functions called by `company-complete-common`. I start typing `\docu`, but nothing happens. Only if type `M-x company-latex-commands` I have `\docum(entclass)` popping up. So my question is the following:
- First, how can I prevent `company-math-symbols-unicode` be active in LateX mode?
- Second, how can I make `company-latex-commands` be called by company when I start typing?

**Comment by vspinu** [comment]
> However it seems that I don't have other 3 functions called by company-complete-common.

You have an error in your elisp code. You need not add a quote in `setq-local` call:

```
;; local configuration for TeX modes
(defun my-latex-mode-setup ()
  (setq-local company-backends
              (append '(company-math-symbols-latex company-latex-commands)
                      company-backends)))
```

**Comment by DSamuylov** [comment]
@vspinu Thank you for your reply! I removed the quote, but the problem remains

``` emacs-lisp
        ;; local configuration for TeX modes¶                         |                 
        (defun my-latex-mode-setup ()¶                                |                 
          (setq-local company-backends¶                               |                 
                      (append '(company-math-symbols-latex company-latex-commands)¶     
                              company-backends)))¶                    |                 

```

**Comment by vspinu** [comment]
>  First, how can I prevent company-math-symbols-unicode be active in LateX mode?

You will have it in latex as you already adding it to global company-backends. So you will need to remove it with `(delq 'company-math-symbols-unicode company-backends)` before assigning it with `setq-local` in your code above.

>   Second, how can I make company-latex-commands be called by company when I start typing?

This should work. I have exactly the same setup. Check that your hook is indeed called by looking at the value of `company-backends` variable in latex mode (with `C-h v company-backends`) and checking if `company-latex-commands` are there. 

You can also try the backend directly. Type `\doc` then call `M-x company-latex-commands`. You should see `\documentclass` commleted.

**Comment by DSamuylov** [comment]
@vspinu Thank you for your help! It seems I managed to fix it. The problem was in the line:

``` emacs-lisp
(add-hook 'LaTeX-mode-hook 'my-latex-mode-setup)
```

I don't know why, but it has to be:

``` emacs-lisp
(add-hook 'tex-mode-hook 'my-latex-mode-setup)
```

**Comment by vspinu** [comment]
You are probably not using auctex then. I will modify the instructions. Thanks.

**Comment by cilia** [comment]
@vspinu, sorry to revive the question, but I'm also having trouble with getting `company-math` to work in `AUCTeX`. I am running `Emacs 24.5.1` in OS X and installed the latest release of `company` and `company-math`. I have tried the suggestions mentioned in this thread, but there is no `company-math` pop-up for any keyword while working in a `.tex` file.

My relevant `.emacs` configs are below.

```
;; Global config for unicode
(add-to-list 'company-backends 'company-math-symbols-unicode)
;; Local configuration for LaTeX
(defun company-latex-mode-setup () 
  (delq 'company-math-symbols-unicode company-backends)
  (setq-local company-backends 
    (append '(company-math-symbols-latex company-latex-commands) company-backends)))

(add-hook 'LaTeX-mode-hook 'company-latex-mode-setup)

;; AUCTeX
(setq TeX-auto-save t)
(setq TeX-parse-self t)
(setq TeX-save-query nil)
(setq TeX-PDF-mode t)
(setq-default TeX-master nil)

(add-hook 'LaTeX-mode-hook 'visual-line-mode)
(add-hook 'LaTeX-mode-hook 'flyspell-mode)
(add-hook 'LaTeX-mode-hook 'LaTeX-math-mode)
(add-hook 'LaTeX-mode-hook 'turn-on-reftex)
(setq reftex-plug-into-AUCTeX t)
```

I am convinced that I have `AUCTeX` activated when I open a `.tex` file, as I can get various `LaTeX-...` variables via `C-h v`. In addition, `C-h v company-backends` gives the following:

![company-backends values](http://i.imgur.com/wupffK8.png)

~~Which puzzles me because both `company-math-symbols-latex` and `company-latex-commands` are missing from the local buffer (which I think is what matters here) whereas `company-math-symbols-unicode` is still there, all despite what is supposed to happen in `company-latex-mode-setup` above.~~

Edit: actually, I think the screenshot shows that both `company-math-symbols-latex` and `company-latex-commands` (as well as `company-math-symbols-unicode`) are there for `company-backends` in the local buffer, as indicated in the first block of text. The fact that `company-math-symbols-unicode` is still there is due to a bug in the `company-latex-mode-setup` function above: it should be `(setq-local company-backends (delq 'company-math-symbols-unicode company-backends))` instead of `(delq 'company-math-symbols-unicode company-backends)`, since the latter does not actually modify `company-backends` (see: http://www.gnu.org/software/emacs/manual/html_node/elisp/Sets-And-Lists.html).

Any suggestion how I can get `company-math` work with `AUCTeX`? Thanks.

**Comment by DSamuylov** [comment]
Maybe a naive question... Did you type anywhere `(require 'company-math)`?

**Comment by cilia** [comment]
No, but I don't think I need one as `company-math` is just a backend for `company` and I've enabled `company` via `(require 'company)` elsewhere.

**Comment by DSamuylov** [comment]
I did both and for me it works... :) I am quite new to emacs and to lisp, but I think `company-math` is a separate package.

**Comment by cilia** [comment]
@DSamuylov you are right, I still need to do the package loading for `company-math`, I've got it working now. Thanks for the pointer.

**Comment by vspinu** [comment]
You don't need to load company-math, nor company if you installed them from MELPA. Relevant functions are autoloaded. That means that if emacs sees such a function in a code, it will automaticaly load the full package.

**Comment by cilia** [comment]
@vspinu Thanks for the clarification. I needed to do `require` for `company-math` because I cannot install it through `melpa-stable` so I compile and install it manually.

Is it possible to make `company-math` available on `melpa-stable` too? Thanks.

**Comment by vspinu** [comment]
Company-math is on the default emacs repository. You should never remove that repository from your repo list. In the `M-x list-packages` you should see

```
  company-math       1.0.1         available  gnu
```

I have now pushed the v.1.0.1 tag to github. It should propagate to MELPA stable automatically. That was an oversight on my sight. Thanks for pointing it out.

**Comment by cilia** [comment]
Great to know that `company-math` is now available from both `GNU` and `MELPA-stable`. Thanks!
